from .models import State, Chamber

states = [
    State(
        name="Alabama",
        abbr="AL",
        capital="Montgomery",
        capital_tz="America/Chicago",
        fips="01",
        unicameral=False,
        legislature_name="Alabama Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=105,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=35,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Alaska",
        abbr="AK",
        capital="Juneau",
        capital_tz="America/Anchorage",
        fips="02",
        unicameral=False,
        legislature_name="Alaska State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=40,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=20,
            seats={
                "A": 1,
                "B": 1,
                "C": 1,
                "D": 1,
                "E": 1,
                "F": 1,
                "G": 1,
                "H": 1,
                "I": 1,
                "J": 1,
                "K": 1,
                "L": 1,
                "M": 1,
                "N": 1,
                "O": 1,
                "P": 1,
                "Q": 1,
                "R": 1,
                "S": 1,
                "T": 1,
            },
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Arizona",
        abbr="AZ",
        capital="Phoenix",
        capital_tz="America/Denver",
        fips="04",
        unicameral=False,
        legislature_name="Arizona State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=60,
            seats={
                "1": 2,
                "2": 2,
                "3": 2,
                "4": 2,
                "5": 2,
                "6": 2,
                "7": 2,
                "8": 2,
                "9": 2,
                "10": 2,
                "11": 2,
                "12": 2,
                "13": 2,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 2,
                "19": 2,
                "20": 2,
                "21": 2,
                "22": 2,
                "23": 2,
                "24": 2,
                "25": 2,
                "26": 2,
                "27": 2,
                "28": 2,
                "29": 2,
                "30": 2,
            },
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=30,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Arkansas",
        abbr="AR",
        capital="Little Rock",
        capital_tz="America/Chicago",
        fips="05",
        unicameral=False,
        legislature_name="Arkansas General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=100,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=35,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="California",
        abbr="CA",
        capital="Sacramento",
        capital_tz="America/Los_Angeles",
        fips="06",
        unicameral=False,
        legislature_name="California State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="Assembly",
            num_seats=80,
            seats=None,
            division_ids=None,
            title="Assemblymember",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=40,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Colorado",
        abbr="CO",
        capital="Denver",
        capital_tz="America/Denver",
        fips="08",
        unicameral=False,
        legislature_name="Colorado General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=65,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=35,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Connecticut",
        abbr="CT",
        capital="Hartford",
        capital_tz="America/New_York",
        fips="09",
        unicameral=False,
        legislature_name="Connecticut General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=151,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=36,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Delaware",
        abbr="DE",
        capital="Dover",
        capital_tz="America/New_York",
        fips="10",
        unicameral=False,
        legislature_name="Delaware General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=41,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=21,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="District of Columbia",
        abbr="DC",
        capital="None",
        capital_tz="America/New_York",
        fips="11",
        unicameral=True,
        legislature_name="Council of the District of Columbia",
        legislature=Chamber(
            chamber_type="unicameral",
            name="Council of the District of Columbia",
            num_seats=13,
            seats={
                "Ward 1": 1,
                "Ward 2": 1,
                "Ward 3": 1,
                "Ward 4": 1,
                "Ward 5": 1,
                "Ward 6": 1,
                "Ward 7": 1,
                "Ward 8": 1,
                "Chairman": 1,
                "At-Large": 4,
            },
            division_ids={
                "Ward 1": "ocd-division/country:us/district:dc/ward:1",
                "Ward 2": "ocd-division/country:us/district:dc/ward:2",
                "Ward 3": "ocd-division/country:us/district:dc/ward:3",
                "Ward 4": "ocd-division/country:us/district:dc/ward:4",
                "Ward 5": "ocd-division/country:us/district:dc/ward:5",
                "Ward 6": "ocd-division/country:us/district:dc/ward:6",
                "Ward 7": "ocd-division/country:us/district:dc/ward:7",
                "Ward 8": "ocd-division/country:us/district:dc/ward:8",
                "Chairman": "ocd-division/country:us/district:dc",
                "At-Large": "ocd-division/country:us/district:dc",
            },
            title="Councilmember",
        ),
    ),
    State(
        name="Florida",
        abbr="FL",
        capital="Tallahassee",
        capital_tz="America/New_York",
        fips="12",
        unicameral=False,
        legislature_name="Florida Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=120,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=40,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Georgia",
        abbr="GA",
        capital="Atlanta",
        capital_tz="America/New_York",
        fips="13",
        unicameral=False,
        legislature_name="Georgia General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=180,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=56,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Hawaii",
        abbr="HI",
        capital="Honolulu",
        capital_tz="Pacific/Honolulu",
        fips="15",
        unicameral=False,
        legislature_name="Hawaii State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=51,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=25,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Idaho",
        abbr="ID",
        capital="Boise",
        capital_tz="America/Denver",
        fips="16",
        unicameral=False,
        legislature_name="Idaho State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=70,
            seats={
                "1": 2,
                "2": 2,
                "3": 2,
                "4": 2,
                "5": 2,
                "6": 2,
                "7": 2,
                "8": 2,
                "9": 2,
                "10": 2,
                "11": 2,
                "12": 2,
                "13": 2,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 2,
                "19": 2,
                "20": 2,
                "21": 2,
                "22": 2,
                "23": 2,
                "24": 2,
                "25": 2,
                "26": 2,
                "27": 2,
                "28": 2,
                "29": 2,
                "30": 2,
                "31": 2,
                "32": 2,
                "33": 2,
                "34": 2,
                "35": 2,
            },
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=35,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Illinois",
        abbr="IL",
        capital="Springfield",
        capital_tz="America/Chicago",
        fips="17",
        unicameral=False,
        legislature_name="Illinois General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=118,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=59,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Indiana",
        abbr="IN",
        capital="Indianapolis",
        capital_tz="America/Indiana/Indianapolis",
        fips="18",
        unicameral=False,
        legislature_name="Indiana General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=100,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=50,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Iowa",
        abbr="IA",
        capital="Des Moines",
        capital_tz="America/Chicago",
        fips="19",
        unicameral=False,
        legislature_name="Iowa General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=100,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=50,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Kansas",
        abbr="KS",
        capital="Topeka",
        capital_tz="America/Chicago",
        fips="20",
        unicameral=False,
        legislature_name="Kansas State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=125,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=40,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Kentucky",
        abbr="KY",
        capital="Frankfort",
        capital_tz="America/New_York",
        fips="21",
        unicameral=False,
        legislature_name="Kentucky General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=100,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=38,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Louisiana",
        abbr="LA",
        capital="Baton Rouge",
        capital_tz="America/Chicago",
        fips="22",
        unicameral=False,
        legislature_name="Louisiana Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=105,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=39,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Maine",
        abbr="ME",
        capital="Augusta",
        capital_tz="America/New_York",
        fips="23",
        unicameral=False,
        legislature_name="Maine Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=151,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=35,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Maryland",
        abbr="MD",
        capital="Annapolis",
        capital_tz="America/New_York",
        fips="24",
        unicameral=False,
        legislature_name="Maryland General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=141,
            seats={
                "1A": 1,
                "1B": 1,
                "1C": 1,
                "2A": 2,
                "2B": 1,
                "3A": 2,
                "3B": 1,
                "4": 3,
                "5": 3,
                "6": 3,
                "7": 3,
                "8": 3,
                "9A": 2,
                "9B": 1,
                "10": 3,
                "11": 3,
                "12": 3,
                "13": 3,
                "14": 3,
                "15": 3,
                "16": 3,
                "17": 3,
                "18": 3,
                "19": 3,
                "20": 3,
                "21": 3,
                "22": 3,
                "23A": 1,
                "23B": 2,
                "24": 3,
                "25": 3,
                "26": 3,
                "27A": 1,
                "27B": 1,
                "27C": 1,
                "28": 3,
                "29A": 1,
                "29B": 1,
                "29C": 1,
                "30A": 2,
                "30B": 1,
                "31A": 1,
                "31B": 2,
                "32": 3,
                "33": 3,
                "34A": 2,
                "34B": 1,
                "35A": 1,
                "35B": 2,
                "36": 3,
                "37A": 1,
                "37B": 2,
                "38A": 1,
                "38B": 1,
                "38C": 1,
                "39": 3,
                "40": 3,
                "41": 3,
                "42A": 1,
                "42B": 2,
                "43": 3,
                "44A": 1,
                "44B": 2,
                "45": 3,
                "46": 3,
                "47A": 2,
                "47B": 1,
            },
            division_ids=None,
            title="Delegate",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=47,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Massachusetts",
        abbr="MA",
        capital="Boston",
        capital_tz="America/New_York",
        fips="25",
        unicameral=False,
        legislature_name="Massachusetts General Court",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=160,
            seats={
                "Tenth Bristol": 1,
                "Tenth Essex": 1,
                "Tenth Hampden": 1,
                "Tenth Middlesex": 1,
                "Tenth Norfolk": 1,
                "Tenth Plymouth": 1,
                "Tenth Suffolk": 1,
                "Tenth Worcester": 1,
                "Eleventh Bristol": 1,
                "Eleventh Essex": 1,
                "Eleventh Hampden": 1,
                "Eleventh Middlesex": 1,
                "Eleventh Norfolk": 1,
                "Eleventh Plymouth": 1,
                "Eleventh Suffolk": 1,
                "Eleventh Worcester": 1,
                "Twelfth Bristol": 1,
                "Twelfth Essex": 1,
                "Twelfth Hampden": 1,
                "Twelfth Middlesex": 1,
                "Twelfth Norfolk": 1,
                "Twelfth Plymouth": 1,
                "Twelfth Suffolk": 1,
                "Twelfth Worcester": 1,
                "Thirteenth Bristol": 1,
                "Thirteenth Essex": 1,
                "Thirteenth Middlesex": 1,
                "Thirteenth Norfolk": 1,
                "Thirteenth Suffolk": 1,
                "Thirteenth Worcester": 1,
                "Fourteenth Bristol": 1,
                "Fourteenth Essex": 1,
                "Fourteenth Middlesex": 1,
                "Fourteenth Norfolk": 1,
                "Fourteenth Suffolk": 1,
                "Fourteenth Worcester": 1,
                "Fifteenth Essex": 1,
                "Fifteenth Middlesex": 1,
                "Fifteenth Norfolk": 1,
                "Fifteenth Suffolk": 1,
                "Fifteenth Worcester": 1,
                "Sixteenth Essex": 1,
                "Sixteenth Middlesex": 1,
                "Sixteenth Suffolk": 1,
                "Sixteenth Worcester": 1,
                "Seventeenth Essex": 1,
                "Seventeenth Middlesex": 1,
                "Seventeenth Suffolk": 1,
                "Seventeenth Worcester": 1,
                "Eighteenth Essex": 1,
                "Eighteenth Middlesex": 1,
                "Eighteenth Suffolk": 1,
                "Eighteenth Worcester": 1,
                "Nineteenth Middlesex": 1,
                "Nineteenth Suffolk": 1,
                "First Barnstable": 1,
                "First Berkshire": 1,
                "First Bristol": 1,
                "First Essex": 1,
                "First Franklin": 1,
                "First Hampden": 1,
                "First Hampshire": 1,
                "First Middlesex": 1,
                "First Norfolk": 1,
                "First Plymouth": 1,
                "First Suffolk": 1,
                "First Worcester": 1,
                "Twentieth Middlesex": 1,
                "Twenty-First Middlesex": 1,
                "Twenty-Second Middlesex": 1,
                "Twenty-Third Middlesex": 1,
                "Twenty-Fourth Middlesex": 1,
                "Twenty-Fifth Middlesex": 1,
                "Twenty-Sixth Middlesex": 1,
                "Twenty-Seventh Middlesex": 1,
                "Twenty-Eighth Middlesex": 1,
                "Twenty-Ninth Middlesex": 1,
                "Second Barnstable": 1,
                "Second Berkshire": 1,
                "Second Bristol": 1,
                "Second Essex": 1,
                "Second Franklin": 1,
                "Second Hampden": 1,
                "Second Hampshire": 1,
                "Second Middlesex": 1,
                "Second Norfolk": 1,
                "Second Plymouth": 1,
                "Second Suffolk": 1,
                "Second Worcester": 1,
                "Thirtieth Middlesex": 1,
                "Thirty-First Middlesex": 1,
                "Thirty-Second Middlesex": 1,
                "Thirty-Third Middlesex": 1,
                "Thirty-Fourth Middlesex": 1,
                "Thirty-Fifth Middlesex": 1,
                "Thirty-Sixth Middlesex": 1,
                "Thirty-Seventh Middlesex": 1,
                "Third Barnstable": 1,
                "Third Berkshire": 1,
                "Third Bristol": 1,
                "Third Essex": 1,
                "Third Hampden": 1,
                "Third Hampshire": 1,
                "Third Middlesex": 1,
                "Third Norfolk": 1,
                "Third Plymouth": 1,
                "Third Suffolk": 1,
                "Third Worcester": 1,
                "Fourth Barnstable": 1,
                "Fourth Berkshire": 1,
                "Fourth Bristol": 1,
                "Fourth Essex": 1,
                "Fourth Hampden": 1,
                "Fourth Middlesex": 1,
                "Fourth Norfolk": 1,
                "Fourth Plymouth": 1,
                "Fourth Suffolk": 1,
                "Fourth Worcester": 1,
                "Fifth Barnstable": 1,
                "Fifth Bristol": 1,
                "Fifth Essex": 1,
                "Fifth Hampden": 1,
                "Fifth Middlesex": 1,
                "Fifth Norfolk": 1,
                "Fifth Plymouth": 1,
                "Fifth Suffolk": 1,
                "Fifth Worcester": 1,
                "Sixth Bristol": 1,
                "Sixth Essex": 1,
                "Sixth Hampden": 1,
                "Sixth Middlesex": 1,
                "Sixth Norfolk": 1,
                "Sixth Plymouth": 1,
                "Sixth Suffolk": 1,
                "Sixth Worcester": 1,
                "Seventh Bristol": 1,
                "Seventh Essex": 1,
                "Seventh Hampden": 1,
                "Seventh Middlesex": 1,
                "Seventh Norfolk": 1,
                "Seventh Plymouth": 1,
                "Seventh Suffolk": 1,
                "Seventh Worcester": 1,
                "Eighth Bristol": 1,
                "Eighth Essex": 1,
                "Eighth Hampden": 1,
                "Eighth Middlesex": 1,
                "Eighth Norfolk": 1,
                "Eighth Plymouth": 1,
                "Eighth Suffolk": 1,
                "Eighth Worcester": 1,
                "Ninth Bristol": 1,
                "Ninth Essex": 1,
                "Ninth Hampden": 1,
                "Ninth Middlesex": 1,
                "Ninth Norfolk": 1,
                "Ninth Plymouth": 1,
                "Ninth Suffolk": 1,
                "Ninth Worcester": 1,
                "Barnstable, Dukes and Nantucket": 1,
            },
            division_ids={
                "Tenth Bristol": "ocd-division/country:us/state:ma/sldl:10th_bristol",
                "Tenth Essex": "ocd-division/country:us/state:ma/sldl:10th_essex",
                "Tenth Hampden": "ocd-division/country:us/state:ma/sldl:10th_hampden",
                "Tenth Middlesex": "ocd-division/country:us/state:ma/sldl:10th_middlesex",
                "Tenth Norfolk": "ocd-division/country:us/state:ma/sldl:10th_norfolk",
                "Tenth Plymouth": "ocd-division/country:us/state:ma/sldl:10th_plymouth",
                "Tenth Suffolk": "ocd-division/country:us/state:ma/sldl:10th_suffolk",
                "Tenth Worcester": "ocd-division/country:us/state:ma/sldl:10th_worcester",
                "Eleventh Bristol": "ocd-division/country:us/state:ma/sldl:11th_bristol",
                "Eleventh Essex": "ocd-division/country:us/state:ma/sldl:11th_essex",
                "Eleventh Hampden": "ocd-division/country:us/state:ma/sldl:11th_hampden",
                "Eleventh Middlesex": "ocd-division/country:us/state:ma/sldl:11th_middlesex",
                "Eleventh Norfolk": "ocd-division/country:us/state:ma/sldl:11th_norfolk",
                "Eleventh Plymouth": "ocd-division/country:us/state:ma/sldl:11th_plymouth",
                "Eleventh Suffolk": "ocd-division/country:us/state:ma/sldl:11th_suffolk",
                "Eleventh Worcester": "ocd-division/country:us/state:ma/sldl:11th_worcester",
                "Twelfth Bristol": "ocd-division/country:us/state:ma/sldl:12th_bristol",
                "Twelfth Essex": "ocd-division/country:us/state:ma/sldl:12th_essex",
                "Twelfth Hampden": "ocd-division/country:us/state:ma/sldl:12th_hampden",
                "Twelfth Middlesex": "ocd-division/country:us/state:ma/sldl:12th_middlesex",
                "Twelfth Norfolk": "ocd-division/country:us/state:ma/sldl:12th_norfolk",
                "Twelfth Plymouth": "ocd-division/country:us/state:ma/sldl:12th_plymouth",
                "Twelfth Suffolk": "ocd-division/country:us/state:ma/sldl:12th_suffolk",
                "Twelfth Worcester": "ocd-division/country:us/state:ma/sldl:12th_worcester",
                "Thirteenth Bristol": "ocd-division/country:us/state:ma/sldl:13th_bristol",
                "Thirteenth Essex": "ocd-division/country:us/state:ma/sldl:13th_essex",
                "Thirteenth Middlesex": "ocd-division/country:us/state:ma/sldl:13th_middlesex",
                "Thirteenth Norfolk": "ocd-division/country:us/state:ma/sldl:13th_norfolk",
                "Thirteenth Suffolk": "ocd-division/country:us/state:ma/sldl:13th_suffolk",
                "Thirteenth Worcester": "ocd-division/country:us/state:ma/sldl:13th_worcester",
                "Fourteenth Bristol": "ocd-division/country:us/state:ma/sldl:14th_bristol",
                "Fourteenth Essex": "ocd-division/country:us/state:ma/sldl:14th_essex",
                "Fourteenth Middlesex": "ocd-division/country:us/state:ma/sldl:14th_middlesex",
                "Fourteenth Norfolk": "ocd-division/country:us/state:ma/sldl:14th_norfolk",
                "Fourteenth Suffolk": "ocd-division/country:us/state:ma/sldl:14th_suffolk",
                "Fourteenth Worcester": "ocd-division/country:us/state:ma/sldl:14th_worcester",
                "Fifteenth Essex": "ocd-division/country:us/state:ma/sldl:15th_essex",
                "Fifteenth Middlesex": "ocd-division/country:us/state:ma/sldl:15th_middlesex",
                "Fifteenth Norfolk": "ocd-division/country:us/state:ma/sldl:15th_norfolk",
                "Fifteenth Suffolk": "ocd-division/country:us/state:ma/sldl:15th_suffolk",
                "Fifteenth Worcester": "ocd-division/country:us/state:ma/sldl:15th_worcester",
                "Sixteenth Essex": "ocd-division/country:us/state:ma/sldl:16th_essex",
                "Sixteenth Middlesex": "ocd-division/country:us/state:ma/sldl:16th_middlesex",
                "Sixteenth Suffolk": "ocd-division/country:us/state:ma/sldl:16th_suffolk",
                "Sixteenth Worcester": "ocd-division/country:us/state:ma/sldl:16th_worcester",
                "Seventeenth Essex": "ocd-division/country:us/state:ma/sldl:17th_essex",
                "Seventeenth Middlesex": "ocd-division/country:us/state:ma/sldl:17th_middlesex",
                "Seventeenth Suffolk": "ocd-division/country:us/state:ma/sldl:17th_suffolk",
                "Seventeenth Worcester": "ocd-division/country:us/state:ma/sldl:17th_worcester",
                "Eighteenth Essex": "ocd-division/country:us/state:ma/sldl:18th_essex",
                "Eighteenth Middlesex": "ocd-division/country:us/state:ma/sldl:18th_middlesex",
                "Eighteenth Suffolk": "ocd-division/country:us/state:ma/sldl:18th_suffolk",
                "Eighteenth Worcester": "ocd-division/country:us/state:ma/sldl:18th_worcester",
                "Nineteenth Middlesex": "ocd-division/country:us/state:ma/sldl:19th_middlesex",
                "Nineteenth Suffolk": "ocd-division/country:us/state:ma/sldl:19th_suffolk",
                "First Barnstable": "ocd-division/country:us/state:ma/sldl:1st_barnstable",
                "First Berkshire": "ocd-division/country:us/state:ma/sldl:1st_berkshire",
                "First Bristol": "ocd-division/country:us/state:ma/sldl:1st_bristol",
                "First Essex": "ocd-division/country:us/state:ma/sldl:1st_essex",
                "First Franklin": "ocd-division/country:us/state:ma/sldl:1st_franklin",
                "First Hampden": "ocd-division/country:us/state:ma/sldl:1st_hampden",
                "First Hampshire": "ocd-division/country:us/state:ma/sldl:1st_hampshire",
                "First Middlesex": "ocd-division/country:us/state:ma/sldl:1st_middlesex",
                "First Norfolk": "ocd-division/country:us/state:ma/sldl:1st_norfolk",
                "First Plymouth": "ocd-division/country:us/state:ma/sldl:1st_plymouth",
                "First Suffolk": "ocd-division/country:us/state:ma/sldl:1st_suffolk",
                "First Worcester": "ocd-division/country:us/state:ma/sldl:1st_worcester",
                "Twentieth Middlesex": "ocd-division/country:us/state:ma/sldl:20th_middlesex",
                "Twenty-First Middlesex": "ocd-division/country:us/state:ma/sldl:21st_middlesex",
                "Twenty-Second Middlesex": "ocd-division/country:us/state:ma/sldl:22nd_middlesex",
                "Twenty-Third Middlesex": "ocd-division/country:us/state:ma/sldl:23rd_middlesex",
                "Twenty-Fourth Middlesex": "ocd-division/country:us/state:ma/sldl:24th_middlesex",
                "Twenty-Fifth Middlesex": "ocd-division/country:us/state:ma/sldl:25th_middlesex",
                "Twenty-Sixth Middlesex": "ocd-division/country:us/state:ma/sldl:26th_middlesex",
                "Twenty-Seventh Middlesex": "ocd-division/country:us/state:ma/sldl:27th_middlesex",
                "Twenty-Eighth Middlesex": "ocd-division/country:us/state:ma/sldl:28th_middlesex",
                "Twenty-Ninth Middlesex": "ocd-division/country:us/state:ma/sldl:29th_middlesex",
                "Second Barnstable": "ocd-division/country:us/state:ma/sldl:2nd_barnstable",
                "Second Berkshire": "ocd-division/country:us/state:ma/sldl:2nd_berkshire",
                "Second Bristol": "ocd-division/country:us/state:ma/sldl:2nd_bristol",
                "Second Essex": "ocd-division/country:us/state:ma/sldl:2nd_essex",
                "Second Franklin": "ocd-division/country:us/state:ma/sldl:2nd_franklin",
                "Second Hampden": "ocd-division/country:us/state:ma/sldl:2nd_hampden",
                "Second Hampshire": "ocd-division/country:us/state:ma/sldl:2nd_hampshire",
                "Second Middlesex": "ocd-division/country:us/state:ma/sldl:2nd_middlesex",
                "Second Norfolk": "ocd-division/country:us/state:ma/sldl:2nd_norfolk",
                "Second Plymouth": "ocd-division/country:us/state:ma/sldl:2nd_plymouth",
                "Second Suffolk": "ocd-division/country:us/state:ma/sldl:2nd_suffolk",
                "Second Worcester": "ocd-division/country:us/state:ma/sldl:2nd_worcester",
                "Thirtieth Middlesex": "ocd-division/country:us/state:ma/sldl:30th_middlesex",
                "Thirty-First Middlesex": "ocd-division/country:us/state:ma/sldl:31st_middlesex",
                "Thirty-Second Middlesex": "ocd-division/country:us/state:ma/sldl:32nd_middlesex",
                "Thirty-Third Middlesex": "ocd-division/country:us/state:ma/sldl:33rd_middlesex",
                "Thirty-Fourth Middlesex": "ocd-division/country:us/state:ma/sldl:34th_middlesex",
                "Thirty-Fifth Middlesex": "ocd-division/country:us/state:ma/sldl:35th_middlesex",
                "Thirty-Sixth Middlesex": "ocd-division/country:us/state:ma/sldl:36th_middlesex",
                "Thirty-Seventh Middlesex": "ocd-division/country:us/state:ma/sldl:37th_middlesex",
                "Third Barnstable": "ocd-division/country:us/state:ma/sldl:3rd_barnstable",
                "Third Berkshire": "ocd-division/country:us/state:ma/sldl:3rd_berkshire",
                "Third Bristol": "ocd-division/country:us/state:ma/sldl:3rd_bristol",
                "Third Essex": "ocd-division/country:us/state:ma/sldl:3rd_essex",
                "Third Hampden": "ocd-division/country:us/state:ma/sldl:3rd_hampden",
                "Third Hampshire": "ocd-division/country:us/state:ma/sldl:3rd_hampshire",
                "Third Middlesex": "ocd-division/country:us/state:ma/sldl:3rd_middlesex",
                "Third Norfolk": "ocd-division/country:us/state:ma/sldl:3rd_norfolk",
                "Third Plymouth": "ocd-division/country:us/state:ma/sldl:3rd_plymouth",
                "Third Suffolk": "ocd-division/country:us/state:ma/sldl:3rd_suffolk",
                "Third Worcester": "ocd-division/country:us/state:ma/sldl:3rd_worcester",
                "Fourth Barnstable": "ocd-division/country:us/state:ma/sldl:4th_barnstable",
                "Fourth Berkshire": "ocd-division/country:us/state:ma/sldl:4th_berkshire",
                "Fourth Bristol": "ocd-division/country:us/state:ma/sldl:4th_bristol",
                "Fourth Essex": "ocd-division/country:us/state:ma/sldl:4th_essex",
                "Fourth Hampden": "ocd-division/country:us/state:ma/sldl:4th_hampden",
                "Fourth Middlesex": "ocd-division/country:us/state:ma/sldl:4th_middlesex",
                "Fourth Norfolk": "ocd-division/country:us/state:ma/sldl:4th_norfolk",
                "Fourth Plymouth": "ocd-division/country:us/state:ma/sldl:4th_plymouth",
                "Fourth Suffolk": "ocd-division/country:us/state:ma/sldl:4th_suffolk",
                "Fourth Worcester": "ocd-division/country:us/state:ma/sldl:4th_worcester",
                "Fifth Barnstable": "ocd-division/country:us/state:ma/sldl:5th_barnstable",
                "Fifth Bristol": "ocd-division/country:us/state:ma/sldl:5th_bristol",
                "Fifth Essex": "ocd-division/country:us/state:ma/sldl:5th_essex",
                "Fifth Hampden": "ocd-division/country:us/state:ma/sldl:5th_hampden",
                "Fifth Middlesex": "ocd-division/country:us/state:ma/sldl:5th_middlesex",
                "Fifth Norfolk": "ocd-division/country:us/state:ma/sldl:5th_norfolk",
                "Fifth Plymouth": "ocd-division/country:us/state:ma/sldl:5th_plymouth",
                "Fifth Suffolk": "ocd-division/country:us/state:ma/sldl:5th_suffolk",
                "Fifth Worcester": "ocd-division/country:us/state:ma/sldl:5th_worcester",
                "Sixth Bristol": "ocd-division/country:us/state:ma/sldl:6th_bristol",
                "Sixth Essex": "ocd-division/country:us/state:ma/sldl:6th_essex",
                "Sixth Hampden": "ocd-division/country:us/state:ma/sldl:6th_hampden",
                "Sixth Middlesex": "ocd-division/country:us/state:ma/sldl:6th_middlesex",
                "Sixth Norfolk": "ocd-division/country:us/state:ma/sldl:6th_norfolk",
                "Sixth Plymouth": "ocd-division/country:us/state:ma/sldl:6th_plymouth",
                "Sixth Suffolk": "ocd-division/country:us/state:ma/sldl:6th_suffolk",
                "Sixth Worcester": "ocd-division/country:us/state:ma/sldl:6th_worcester",
                "Seventh Bristol": "ocd-division/country:us/state:ma/sldl:7th_bristol",
                "Seventh Essex": "ocd-division/country:us/state:ma/sldl:7th_essex",
                "Seventh Hampden": "ocd-division/country:us/state:ma/sldl:7th_hampden",
                "Seventh Middlesex": "ocd-division/country:us/state:ma/sldl:7th_middlesex",
                "Seventh Norfolk": "ocd-division/country:us/state:ma/sldl:7th_norfolk",
                "Seventh Plymouth": "ocd-division/country:us/state:ma/sldl:7th_plymouth",
                "Seventh Suffolk": "ocd-division/country:us/state:ma/sldl:7th_suffolk",
                "Seventh Worcester": "ocd-division/country:us/state:ma/sldl:7th_worcester",
                "Eighth Bristol": "ocd-division/country:us/state:ma/sldl:8th_bristol",
                "Eighth Essex": "ocd-division/country:us/state:ma/sldl:8th_essex",
                "Eighth Hampden": "ocd-division/country:us/state:ma/sldl:8th_hampden",
                "Eighth Middlesex": "ocd-division/country:us/state:ma/sldl:8th_middlesex",
                "Eighth Norfolk": "ocd-division/country:us/state:ma/sldl:8th_norfolk",
                "Eighth Plymouth": "ocd-division/country:us/state:ma/sldl:8th_plymouth",
                "Eighth Suffolk": "ocd-division/country:us/state:ma/sldl:8th_suffolk",
                "Eighth Worcester": "ocd-division/country:us/state:ma/sldl:8th_worcester",
                "Ninth Bristol": "ocd-division/country:us/state:ma/sldl:9th_bristol",
                "Ninth Essex": "ocd-division/country:us/state:ma/sldl:9th_essex",
                "Ninth Hampden": "ocd-division/country:us/state:ma/sldl:9th_hampden",
                "Ninth Middlesex": "ocd-division/country:us/state:ma/sldl:9th_middlesex",
                "Ninth Norfolk": "ocd-division/country:us/state:ma/sldl:9th_norfolk",
                "Ninth Plymouth": "ocd-division/country:us/state:ma/sldl:9th_plymouth",
                "Ninth Suffolk": "ocd-division/country:us/state:ma/sldl:9th_suffolk",
                "Ninth Worcester": "ocd-division/country:us/state:ma/sldl:9th_worcester",
                "Barnstable, Dukes and Nantucket": "ocd-division/country:us/state:ma/sldl:barnstable_dukes_and_nantucket",
            },
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=40,
            seats={
                "Bristol and Norfolk": 1,
                "Cape and Islands": 1,
                "Fifth Middlesex": 1,
                "First Bristol and Plymouth": 1,
                "First Essex": 1,
                "First Essex and Middlesex": 1,
                "First Hampden and Hampshire": 1,
                "First Middlesex": 1,
                "First Middlesex and Norfolk": 1,
                "First Plymouth and Bristol": 1,
                "First Suffolk": 1,
                "First Suffolk and Middlesex": 1,
                "First Worcester": 1,
                "Fourth Middlesex": 1,
                "Hampden": 1,
                "Berkshire, Hampshire, Franklin and Hampden": 1,
                "Middlesex and Suffolk": 1,
                "Middlesex and Worcester": 1,
                "Norfolk, Bristol and Middlesex": 1,
                "Norfolk, Bristol and Plymouth": 1,
                "Norfolk and Plymouth": 1,
                "Norfolk and Suffolk": 1,
                "Plymouth and Barnstable": 1,
                "Plymouth and Norfolk": 1,
                "Second Bristol and Plymouth": 1,
                "Second Essex": 1,
                "Second Essex and Middlesex": 1,
                "Second Hampden and Hampshire": 1,
                "Second Middlesex": 1,
                "Second Middlesex and Norfolk": 1,
                "Second Plymouth and Bristol": 1,
                "Second Suffolk": 1,
                "Second Suffolk and Middlesex": 1,
                "Second Worcester": 1,
                "Third Essex": 1,
                "Third Middlesex": 1,
                "Worcester and Middlesex": 1,
                "Worcester and Norfolk": 1,
                "Worcester, Hampden, Hampshire and Middlesex": 1,
                "Hampshire, Franklin and Worcester": 1,
            },
            division_ids={
                "Berkshire, Hampshire, Franklin and Hampden": "ocd-division/country:us/state:ma/sldu:berkshire_hampshire_franklin_and_hampden",
                "Bristol and Norfolk": "ocd-division/country:us/state:ma/sldu:bristol_and_norfolk",
                "Cape and Islands": "ocd-division/country:us/state:ma/sldu:cape_and_islands",
                "Fifth Middlesex": "ocd-division/country:us/state:ma/sldu:5th_middlesex",
                "First Bristol and Plymouth": "ocd-division/country:us/state:ma/sldu:1st_bristol_and_plymouth",
                "First Essex": "ocd-division/country:us/state:ma/sldu:1st_essex",
                "First Essex and Middlesex": "ocd-division/country:us/state:ma/sldu:1st_essex_and_middlesex",
                "First Hampden and Hampshire": "ocd-division/country:us/state:ma/sldu:1st_hampden_and_hampshire",
                "First Middlesex": "ocd-division/country:us/state:ma/sldu:1st_middlesex",
                "First Middlesex and Norfolk": "ocd-division/country:us/state:ma/sldu:1st_middlesex_and_norfolk",
                "First Plymouth and Bristol": "ocd-division/country:us/state:ma/sldu:1st_plymouth_and_bristol",
                "First Suffolk": "ocd-division/country:us/state:ma/sldu:1st_suffolk",
                "First Suffolk and Middlesex": "ocd-division/country:us/state:ma/sldu:1st_suffolk_and_middlesex",
                "First Worcester": "ocd-division/country:us/state:ma/sldu:1st_worcester",
                "Fourth Middlesex": "ocd-division/country:us/state:ma/sldu:4th_middlesex",
                "Hampden": "ocd-division/country:us/state:ma/sldu:hampden",
                "Hampshire, Franklin and Worcester": "ocd-division/country:us/state:ma/sldu:hampshire_franklin_and_worcester",
                "Middlesex and Suffolk": "ocd-division/country:us/state:ma/sldu:middlesex_and_suffolk",
                "Middlesex and Worcester": "ocd-division/country:us/state:ma/sldu:middlesex_and_worcester",
                "Norfolk, Bristol and Middlesex": "ocd-division/country:us/state:ma/sldu:norfolk_bristol_and_middlesex",
                "Norfolk, Bristol and Plymouth": "ocd-division/country:us/state:ma/sldu:norfolk_bristol_and_plymouth",
                "Norfolk and Plymouth": "ocd-division/country:us/state:ma/sldu:norfolk_and_plymouth",
                "Norfolk and Suffolk": "ocd-division/country:us/state:ma/sldu:norfolk_and_suffolk",
                "Plymouth and Barnstable": "ocd-division/country:us/state:ma/sldu:plymouth_and_barnstable",
                "Plymouth and Norfolk": "ocd-division/country:us/state:ma/sldu:plymouth_and_norfolk",
                "Second Bristol and Plymouth": "ocd-division/country:us/state:ma/sldu:2nd_bristol_and_plymouth",
                "Second Essex": "ocd-division/country:us/state:ma/sldu:2nd_essex",
                "Second Essex and Middlesex": "ocd-division/country:us/state:ma/sldu:2nd_essex_and_middlesex",
                "Second Hampden and Hampshire": "ocd-division/country:us/state:ma/sldu:2nd_hampden_and_hampshire",
                "Second Middlesex": "ocd-division/country:us/state:ma/sldu:2nd_middlesex",
                "Second Middlesex and Norfolk": "ocd-division/country:us/state:ma/sldu:2nd_middlesex_and_norfolk",
                "Second Plymouth and Bristol": "ocd-division/country:us/state:ma/sldu:2nd_plymouth_and_bristol",
                "Second Suffolk": "ocd-division/country:us/state:ma/sldu:2nd_suffolk",
                "Second Suffolk and Middlesex": "ocd-division/country:us/state:ma/sldu:2nd_suffolk_and_middlesex",
                "Second Worcester": "ocd-division/country:us/state:ma/sldu:2nd_worcester",
                "Third Essex": "ocd-division/country:us/state:ma/sldu:3rd_essex",
                "Third Middlesex": "ocd-division/country:us/state:ma/sldu:3rd_middlesex",
                "Worcester, Hampden, Hampshire and Middlesex": "ocd-division/country:us/state:ma/sldu:worcester_hampden_hampshire_and_middlesex",
                "Worcester and Middlesex": "ocd-division/country:us/state:ma/sldu:worcester_and_middlesex",
                "Worcester and Norfolk": "ocd-division/country:us/state:ma/sldu:worcester_and_norfolk",
            },
            title="Senator",
        ),
    ),
    State(
        name="Michigan",
        abbr="MI",
        capital="Lansing",
        capital_tz="America/New_York",
        fips="26",
        unicameral=False,
        legislature_name="Michigan Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=110,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=38,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Minnesota",
        abbr="MN",
        capital="Saint Paul",
        capital_tz="America/Chicago",
        fips="27",
        unicameral=False,
        legislature_name="Minnesota State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=134,
            seats={
                "1A": 1,
                "1B": 1,
                "2A": 1,
                "2B": 1,
                "3A": 1,
                "3B": 1,
                "4A": 1,
                "4B": 1,
                "5A": 1,
                "5B": 1,
                "6A": 1,
                "6B": 1,
                "7A": 1,
                "7B": 1,
                "8A": 1,
                "8B": 1,
                "9A": 1,
                "9B": 1,
                "10A": 1,
                "10B": 1,
                "11A": 1,
                "11B": 1,
                "12A": 1,
                "12B": 1,
                "13A": 1,
                "13B": 1,
                "14A": 1,
                "14B": 1,
                "15A": 1,
                "15B": 1,
                "16A": 1,
                "16B": 1,
                "17A": 1,
                "17B": 1,
                "18A": 1,
                "18B": 1,
                "19A": 1,
                "19B": 1,
                "20A": 1,
                "20B": 1,
                "21A": 1,
                "21B": 1,
                "22A": 1,
                "22B": 1,
                "23A": 1,
                "23B": 1,
                "24A": 1,
                "24B": 1,
                "25A": 1,
                "25B": 1,
                "26A": 1,
                "26B": 1,
                "27A": 1,
                "27B": 1,
                "28A": 1,
                "28B": 1,
                "29A": 1,
                "29B": 1,
                "30A": 1,
                "30B": 1,
                "31A": 1,
                "31B": 1,
                "32A": 1,
                "32B": 1,
                "33A": 1,
                "33B": 1,
                "34A": 1,
                "34B": 1,
                "35A": 1,
                "35B": 1,
                "36A": 1,
                "36B": 1,
                "37A": 1,
                "37B": 1,
                "38A": 1,
                "38B": 1,
                "39A": 1,
                "39B": 1,
                "40A": 1,
                "40B": 1,
                "41A": 1,
                "41B": 1,
                "42A": 1,
                "42B": 1,
                "43A": 1,
                "43B": 1,
                "44A": 1,
                "44B": 1,
                "45A": 1,
                "45B": 1,
                "46A": 1,
                "46B": 1,
                "47A": 1,
                "47B": 1,
                "48A": 1,
                "48B": 1,
                "49A": 1,
                "49B": 1,
                "50A": 1,
                "50B": 1,
                "51A": 1,
                "51B": 1,
                "52A": 1,
                "52B": 1,
                "53A": 1,
                "53B": 1,
                "54A": 1,
                "54B": 1,
                "55A": 1,
                "55B": 1,
                "56A": 1,
                "56B": 1,
                "57A": 1,
                "57B": 1,
                "58A": 1,
                "58B": 1,
                "59A": 1,
                "59B": 1,
                "60A": 1,
                "60B": 1,
                "61A": 1,
                "61B": 1,
                "62A": 1,
                "62B": 1,
                "63A": 1,
                "63B": 1,
                "64A": 1,
                "64B": 1,
                "65A": 1,
                "65B": 1,
                "66A": 1,
                "66B": 1,
                "67A": 1,
                "67B": 1,
            },
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=67,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Mississippi",
        abbr="MS",
        capital="Jackson",
        capital_tz="America/Chicago",
        fips="28",
        unicameral=False,
        legislature_name="Mississippi Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=122,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=52,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Missouri",
        abbr="MO",
        capital="Jefferson City",
        capital_tz="America/Chicago",
        fips="29",
        unicameral=False,
        legislature_name="Missouri General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=163,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=34,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Montana",
        abbr="MT",
        capital="Helena",
        capital_tz="America/Denver",
        fips="30",
        unicameral=False,
        legislature_name="Montana Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=100,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=50,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Nebraska",
        abbr="NE",
        capital="Lincoln",
        capital_tz="America/Chicago",
        fips="31",
        unicameral=True,
        legislature_name="Nebraska Legislature",
        legislature=Chamber(
            chamber_type="unicameral",
            name="Nebraska Legislature",
            num_seats=49,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Nevada",
        abbr="NV",
        capital="Carson City",
        capital_tz="America/Los_Angeles",
        fips="32",
        unicameral=False,
        legislature_name="Nevada Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="Assembly",
            num_seats=42,
            seats=None,
            division_ids=None,
            title="Assembly Member",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=21,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="New Hampshire",
        abbr="NH",
        capital="Concord",
        capital_tz="America/New_York",
        fips="33",
        unicameral=False,
        legislature_name="New Hampshire General Court",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=400,
            seats={
                "Belknap 1": 1,
                "Belknap 2": 4,
                "Belknap 3": 4,
                "Belknap 4": 2,
                "Belknap 5": 2,
                "Belknap 6": 2,
                "Belknap 7": 1,
                "Belknap 8": 1,
                "Belknap 9": 1,
                "Carroll 1": 1,
                "Carroll 2": 3,
                "Carroll 3": 2,
                "Carroll 4": 2,
                "Carroll 5": 3,
                "Carroll 6": 2,
                "Carroll 7": 1,
                "Carroll 8": 1,
                "Cheshire 1": 4,
                "Cheshire 2": 1,
                "Cheshire 3": 1,
                "Cheshire 4": 1,
                "Cheshire 5": 1,
                "Cheshire 6": 1,
                "Cheshire 7": 1,
                "Cheshire 8": 1,
                "Cheshire 9": 2,
                "Cheshire 10": 1,
                "Cheshire 11": 2,
                "Cheshire 12": 2,
                "Cheshire 13": 1,
                "Cheshire 14": 1,
                "Cheshire 15": 1,
                "Cheshire 16": 2,
                "Coos 1": 2,
                "Coos 2": 1,
                "Coos 3": 3,
                "Coos 4": 1,
                "Coos 5": 1,
                "Coos 6": 1,
                "Coos 7": 1,
                "Grafton 1": 2,
                "Grafton 2": 1,
                "Grafton 3": 1,
                "Grafton 4": 1,
                "Grafton 5": 1,
                "Grafton 6": 1,
                "Grafton 7": 1,
                "Grafton 8": 3,
                "Grafton 9": 2,
                "Grafton 10": 1,
                "Grafton 11": 1,
                "Grafton 12": 4,
                "Grafton 13": 4,
                "Grafton 14": 1,
                "Grafton 15": 1,
                "Grafton 16": 1,
                "Grafton 17": 1,
                "Hillsborough 1": 2,
                "Hillsborough 2": 3,
                "Hillsborough 3": 1,
                "Hillsborough 4": 2,
                "Hillsborough 5": 2,
                "Hillsborough 6": 5,
                "Hillsborough 7": 6,
                "Hillsborough 8": 2,
                "Hillsborough 9": 2,
                "Hillsborough 10": 2,
                "Hillsborough 11": 2,
                "Hillsborough 12": 2,
                "Hillsborough 13": 2,
                "Hillsborough 14": 2,
                "Hillsborough 15": 2,
                "Hillsborough 16": 2,
                "Hillsborough 17": 2,
                "Hillsborough 18": 2,
                "Hillsborough 19": 2,
                "Hillsborough 20": 2,
                "Hillsborough 21": 8,
                "Hillsborough 22": 3,
                "Hillsborough 23": 4,
                "Hillsborough 24": 2,
                "Hillsborough 25": 2,
                "Hillsborough 26": 2,
                "Hillsborough 27": 2,
                "Hillsborough 28": 3,
                "Hillsborough 29": 3,
                "Hillsborough 30": 3,
                "Hillsborough 31": 3,
                "Hillsborough 32": 3,
                "Hillsborough 33": 3,
                "Hillsborough 34": 3,
                "Hillsborough 35": 3,
                "Hillsborough 36": 3,
                "Hillsborough 37": 11,
                "Hillsborough 38": 2,
                "Hillsborough 39": 1,
                "Hillsborough 40": 1,
                "Hillsborough 41": 1,
                "Hillsborough 42": 2,
                "Hillsborough 43": 3,
                "Hillsborough 44": 2,
                "Hillsborough 45": 2,
                "Merrimack 1": 1,
                "Merrimack 2": 2,
                "Merrimack 3": 2,
                "Merrimack 4": 1,
                "Merrimack 5": 2,
                "Merrimack 6": 2,
                "Merrimack 7": 1,
                "Merrimack 8": 1,
                "Merrimack 9": 2,
                "Merrimack 10": 3,
                "Merrimack 11": 1,
                "Merrimack 12": 1,
                "Merrimack 13": 1,
                "Merrimack 14": 1,
                "Merrimack 15": 1,
                "Merrimack 16": 1,
                "Merrimack 17": 1,
                "Merrimack 18": 1,
                "Merrimack 19": 1,
                "Merrimack 20": 3,
                "Merrimack 21": 2,
                "Merrimack 22": 1,
                "Merrimack 23": 3,
                "Merrimack 24": 4,
                "Merrimack 25": 1,
                "Merrimack 26": 1,
                "Merrimack 27": 2,
                "Merrimack 28": 1,
                "Merrimack 29": 1,
                "Rockingham 1": 1,
                "Rockingham 2": 3,
                "Rockingham 3": 3,
                "Rockingham 4": 5,
                "Rockingham 5": 7,
                "Rockingham 6": 10,
                "Rockingham 7": 4,
                "Rockingham 8": 9,
                "Rockingham 9": 2,
                "Rockingham 10": 1,
                "Rockingham 11": 1,
                "Rockingham 12": 1,
                "Rockingham 13": 4,
                "Rockingham 14": 4,
                "Rockingham 15": 1,
                "Rockingham 16": 1,
                "Rockingham 17": 3,
                "Rockingham 18": 4,
                "Rockingham 19": 2,
                "Rockingham 20": 3,
                "Rockingham 21": 4,
                "Rockingham 22": 1,
                "Rockingham 23": 1,
                "Rockingham 24": 2,
                "Rockingham 25": 1,
                "Rockingham 26": 1,
                "Rockingham 27": 1,
                "Rockingham 28": 1,
                "Rockingham 29": 1,
                "Rockingham 30": 1,
                "Rockingham 31": 1,
                "Rockingham 32": 1,
                "Rockingham 33": 1,
                "Rockingham 34": 1,
                "Rockingham 35": 1,
                "Rockingham 36": 1,
                "Rockingham 37": 1,
                "Strafford 1": 2,
                "Strafford 2": 2,
                "Strafford 3": 2,
                "Strafford 4": 2,
                "Strafford 5": 1,
                "Strafford 6": 5,
                "Strafford 7": 1,
                "Strafford 8": 1,
                "Strafford 9": 1,
                "Strafford 10": 1,
                "Strafford 11": 1,
                "Strafford 12": 1,
                "Strafford 13": 1,
                "Strafford 14": 1,
                "Strafford 15": 1,
                "Strafford 16": 1,
                "Strafford 17": 3,
                "Strafford 18": 3,
                "Strafford 19": 1,
                "Strafford 20": 1,
                "Strafford 21": 1,
                "Strafford 22": 1,
                "Strafford 23": 1,
                "Strafford 24": 1,
                "Strafford 25": 1,
                "Sullivan 1": 2,
                "Sullivan 2": 1,
                "Sullivan 3": 1,
                "Sullivan 4": 1,
                "Sullivan 5": 1,
                "Sullivan 6": 2,
                "Sullivan 7": 1,
                "Sullivan 8": 1,
                "Sullivan 9": 1,
                "Sullivan 10": 1,
                "Sullivan 11": 1,
            },
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=24,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="New Jersey",
        abbr="NJ",
        capital="Trenton",
        capital_tz="America/New_York",
        fips="34",
        unicameral=False,
        legislature_name="New jersey Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="Assembly",
            num_seats=80,
            seats={
                "1": 2,
                "2": 2,
                "3": 2,
                "4": 2,
                "5": 2,
                "6": 2,
                "7": 2,
                "8": 2,
                "9": 2,
                "10": 2,
                "11": 2,
                "12": 2,
                "13": 2,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 2,
                "19": 2,
                "20": 2,
                "21": 2,
                "22": 2,
                "23": 2,
                "24": 2,
                "25": 2,
                "26": 2,
                "27": 2,
                "28": 2,
                "29": 2,
                "30": 2,
                "31": 2,
                "32": 2,
                "33": 2,
                "34": 2,
                "35": 2,
                "36": 2,
                "37": 2,
                "38": 2,
                "39": 2,
                "40": 2,
            },
            division_ids=None,
            title="Assembly Member",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=40,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="New Mexico",
        abbr="NM",
        capital="Santa Fe",
        capital_tz="America/Chicago",
        fips="35",
        unicameral=False,
        legislature_name="New Mexico Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=70,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=42,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="New York",
        abbr="NY",
        capital="Albany",
        capital_tz="America/New_York",
        fips="36",
        unicameral=False,
        legislature_name="New York Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="Assembly",
            num_seats=150,
            seats=None,
            division_ids=None,
            title="Assembly Member",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=63,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="North Carolina",
        abbr="NC",
        capital="Raleigh",
        capital_tz="America/New_York",
        fips="37",
        unicameral=False,
        legislature_name="North Carolina General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=120,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=50,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="North Dakota",
        abbr="ND",
        capital="Bismarck",
        capital_tz="America/North_Dakota/Center",
        fips="38",
        unicameral=False,
        legislature_name="North Dakota Legislative Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=94,
            seats={
                "1": 2,
                "2": 2,
                "3": 2,
                "4": 2,
                "5": 2,
                "6": 2,
                "7": 2,
                "8": 2,
                "9": 2,
                "10": 2,
                "11": 2,
                "12": 2,
                "13": 2,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 2,
                "19": 2,
                "20": 2,
                "21": 2,
                "22": 2,
                "23": 2,
                "24": 2,
                "25": 2,
                "26": 2,
                "27": 2,
                "28": 2,
                "29": 2,
                "30": 2,
                "31": 2,
                "32": 2,
                "33": 2,
                "34": 2,
                "35": 2,
                "36": 2,
                "37": 2,
                "38": 2,
                "39": 2,
                "40": 2,
                "41": 2,
                "42": 2,
                "43": 2,
                "44": 2,
                "45": 2,
                "46": 2,
                "47": 2,
            },
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=47,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Ohio",
        abbr="OH",
        capital="Columbus",
        capital_tz="America/New_York",
        fips="39",
        unicameral=False,
        legislature_name="Ohio General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=99,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=33,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Oklahoma",
        abbr="OK",
        capital="Oklahoma City",
        capital_tz="America/Chicago",
        fips="40",
        unicameral=False,
        legislature_name="Oklahoma Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=101,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=48,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Oregon",
        abbr="OR",
        capital="Salem",
        capital_tz="America/Los_Angeles",
        fips="41",
        unicameral=False,
        legislature_name="Oregon Legislative Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=60,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=30,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Pennsylvania",
        abbr="PA",
        capital="Harrisburg",
        capital_tz="America/New_York",
        fips="42",
        unicameral=False,
        legislature_name="Pennsylvania General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=203,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=50,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Rhode Island",
        abbr="RI",
        capital="Providence",
        capital_tz="America/New_York",
        fips="44",
        unicameral=False,
        legislature_name="Rhode Island General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=75,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=38,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="South Carolina",
        abbr="SC",
        capital="Columbia",
        capital_tz="America/New_York",
        fips="45",
        unicameral=False,
        legislature_name="South Carolina Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=124,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=46,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="South Dakota",
        abbr="SD",
        capital="Pierre",
        capital_tz="America/Chicago",
        fips="46",
        unicameral=False,
        legislature_name="South Dakota State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=70,
            seats={
                "1": 2,
                "2": 2,
                "3": 2,
                "4": 2,
                "5": 2,
                "6": 2,
                "7": 2,
                "8": 2,
                "9": 2,
                "10": 2,
                "11": 2,
                "12": 2,
                "13": 2,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 2,
                "19": 2,
                "20": 2,
                "21": 2,
                "22": 2,
                "23": 2,
                "24": 2,
                "25": 2,
                "26A": 1,
                "26B": 1,
                "27": 2,
                "28A": 1,
                "28B": 1,
                "29": 2,
                "30": 2,
                "31": 2,
                "32": 2,
                "33": 2,
                "34": 2,
                "35": 2,
            },
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=35,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Tennessee",
        abbr="TN",
        capital="Nashville",
        capital_tz="America/Chicago",
        fips="47",
        unicameral=False,
        legislature_name="Tennessee General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=99,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=33,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Texas",
        abbr="TX",
        capital="Austin",
        capital_tz="America/Chicago",
        fips="48",
        unicameral=False,
        legislature_name="Texas Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=150,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=31,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Utah",
        abbr="UT",
        capital="Salt Lake City",
        capital_tz="America/Denver",
        fips="49",
        unicameral=False,
        legislature_name="Utah State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=75,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=29,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Vermont",
        abbr="VT",
        capital="Montpelier",
        capital_tz="America/New_York",
        fips="50",
        unicameral=False,
        legislature_name="Vermont General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=150,
            seats={
                "Addison-1": 2,
                "Addison-2": 1,
                "Addison-3": 2,
                "Addison-4": 2,
                "Addison-5": 1,
                "Addison-Rutland": 1,
                "Bennington-1": 1,
                "Bennington-2-1": 2,
                "Bennington-2-2": 2,
                "Bennington-3": 1,
                "Bennington-4": 2,
                "Bennington-Rutland": 1,
                "Caledonia-1": 1,
                "Caledonia-2": 1,
                "Caledonia-3": 2,
                "Caledonia-4": 2,
                "Caledonia-Washington": 1,
                "Chittenden-10": 2,
                "Chittenden-1": 1,
                "Chittenden-2": 2,
                "Chittenden-3": 2,
                "Chittenden-4-1": 1,
                "Chittenden-4-2": 1,
                "Chittenden-5-1": 1,
                "Chittenden-5-2": 1,
                "Chittenden-6-1": 2,
                "Chittenden-6-2": 1,
                "Chittenden-6-3": 2,
                "Chittenden-6-4": 2,
                "Chittenden-6-5": 2,
                "Chittenden-6-6": 1,
                "Chittenden-6-7": 2,
                "Chittenden-7-1": 1,
                "Chittenden-7-2": 1,
                "Chittenden-7-3": 1,
                "Chittenden-7-4": 1,
                "Chittenden-8-1": 2,
                "Chittenden-8-2": 2,
                "Chittenden-8-3": 1,
                "Chittenden-9-1": 2,
                "Chittenden-9-2": 2,
                "Essex-Caledonia": 1,
                "Essex-Caledonia-Orleans": 1,
                "Franklin-1": 1,
                "Franklin-2": 1,
                "Franklin-3-1": 2,
                "Franklin-3-2": 1,
                "Franklin-4": 2,
                "Franklin-5": 2,
                "Franklin-6": 1,
                "Franklin-7": 1,
                "Grand Isle-Chittenden": 2,
                "Lamoille-1": 1,
                "Lamoille-2": 2,
                "Lamoille-3": 1,
                "Lamoille-Washington": 2,
                "Orange-1": 2,
                "Orange-2": 1,
                "Orange-Caledonia": 1,
                "Orange-Washington-Addison": 2,
                "Orleans-1": 2,
                "Orleans-2": 2,
                "Orleans-Caledonia": 2,
                "Orleans-Lamoille": 1,
                "Rutland-1": 1,
                "Rutland-2": 2,
                "Rutland-3": 2,
                "Rutland-4": 1,
                "Rutland-5-1": 1,
                "Rutland-5-2": 1,
                "Rutland-5-3": 1,
                "Rutland-5-4": 1,
                "Rutland-6": 2,
                "Rutland-Bennington": 1,
                "Rutland-Windsor-1": 1,
                "Rutland-Windsor-2": 1,
                "Washington-1": 2,
                "Washington-2": 2,
                "Washington-3": 2,
                "Washington-4": 2,
                "Washington-5": 1,
                "Washington-6": 1,
                "Washington-7": 2,
                "Washington-Chittenden": 2,
                "Windham-1": 1,
                "Windham-2-1": 1,
                "Windham-2-2": 1,
                "Windham-2-3": 1,
                "Windham-3": 2,
                "Windham-4": 2,
                "Windham-5": 1,
                "Windham-6": 1,
                "Windham-Bennington": 1,
                "Windham-Bennington-Windsor": 1,
                "Windsor-1": 2,
                "Windsor-2": 1,
                "Windsor-3-1": 1,
                "Windsor-3-2": 2,
                "Windsor-4-1": 1,
                "Windsor-4-2": 2,
                "Windsor-5": 1,
                "Windsor-Orange-1": 1,
                "Windsor-Orange-2": 2,
                "Windsor-Rutland": 1,
            },
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=30,
            seats={
                "Addison": 2,
                "Bennington": 2,
                "Caledonia": 2,
                "Chittenden": 6,
                "Essex-Orleans": 2,
                "Franklin": 2,
                "Grand Isle": 1,
                "Lamoille": 1,
                "Orange": 1,
                "Rutland": 3,
                "Washington": 3,
                "Windham": 2,
                "Windsor": 3,
            },
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Virginia",
        abbr="VA",
        capital="Richmond",
        capital_tz="America/New_York",
        fips="51",
        unicameral=False,
        legislature_name="Virginia General Assembly",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=100,
            seats=None,
            division_ids=None,
            title="Delegate",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=40,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Washington",
        abbr="WA",
        capital="Olympia",
        capital_tz="America/Los_Angeles",
        fips="53",
        unicameral=False,
        legislature_name="Washington State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=98,
            seats={
                "1": 2,
                "2": 2,
                "3": 2,
                "4": 2,
                "5": 2,
                "6": 2,
                "7": 2,
                "8": 2,
                "9": 2,
                "10": 2,
                "11": 2,
                "12": 2,
                "13": 2,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
                "18": 2,
                "19": 2,
                "20": 2,
                "21": 2,
                "22": 2,
                "23": 2,
                "24": 2,
                "25": 2,
                "26": 2,
                "27": 2,
                "28": 2,
                "29": 2,
                "30": 2,
                "31": 2,
                "32": 2,
                "33": 2,
                "34": 2,
                "35": 2,
                "36": 2,
                "37": 2,
                "38": 2,
                "39": 2,
                "40": 2,
                "41": 2,
                "42": 2,
                "43": 2,
                "44": 2,
                "45": 2,
                "46": 2,
                "47": 2,
                "48": 2,
                "49": 2,
            },
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=49,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="West Virginia",
        abbr="WV",
        capital="Charleston",
        capital_tz="America/New_York",
        fips="54",
        unicameral=False,
        legislature_name="West Virginia Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=100,
            seats={
                "1": 2,
                "2": 1,
                "3": 2,
                "4": 2,
                "5": 1,
                "6": 1,
                "7": 1,
                "8": 1,
                "9": 1,
                "10": 3,
                "11": 1,
                "12": 1,
                "13": 2,
                "14": 1,
                "15": 1,
                "16": 3,
                "17": 2,
                "18": 1,
                "19": 2,
                "20": 1,
                "21": 1,
                "22": 2,
                "23": 1,
                "24": 2,
                "25": 1,
                "26": 1,
                "27": 3,
                "28": 2,
                "29": 1,
                "30": 1,
                "31": 1,
                "32": 3,
                "33": 1,
                "34": 1,
                "35": 4,
                "36": 3,
                "37": 1,
                "38": 1,
                "39": 1,
                "40": 1,
                "41": 1,
                "42": 2,
                "43": 2,
                "44": 1,
                "45": 1,
                "46": 1,
                "47": 1,
                "48": 4,
                "49": 1,
                "50": 3,
                "51": 5,
                "52": 1,
                "53": 1,
                "54": 1,
                "55": 1,
                "56": 1,
                "57": 1,
                "58": 1,
                "59": 1,
                "60": 1,
                "61": 1,
                "62": 1,
                "63": 1,
                "64": 1,
                "65": 1,
                "66": 1,
                "67": 1,
            },
            division_ids=None,
            title="Delegate",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=34,
            seats={
                "1": 2,
                "2": 2,
                "3": 2,
                "4": 2,
                "5": 2,
                "6": 2,
                "7": 2,
                "8": 2,
                "9": 2,
                "10": 2,
                "11": 2,
                "12": 2,
                "13": 2,
                "14": 2,
                "15": 2,
                "16": 2,
                "17": 2,
            },
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Wisconsin",
        abbr="WI",
        capital="Madison",
        capital_tz="America/Chicago",
        fips="55",
        unicameral=False,
        legislature_name="Wisconsin State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="Assembly",
            num_seats=99,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=33,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
    State(
        name="Wyoming",
        abbr="WY",
        capital="Cheyenne",
        capital_tz="America/Denver",
        fips="56",
        unicameral=False,
        legislature_name="Wyoming State Legislature",
        lower=Chamber(
            chamber_type="lower",
            name="House",
            num_seats=60,
            seats=None,
            division_ids=None,
            title="Representative",
        ),
        upper=Chamber(
            chamber_type="upper",
            name="Senate",
            num_seats=30,
            seats=None,
            division_ids=None,
            title="Senator",
        ),
    ),
]
