# Generated by Django 3.0.5 on 2020-04-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("data", "0005_auto_20200423_1100")]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="first_action_date",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AddField(
            model_name="bill",
            name="latest_action_date",
            field=models.CharField(default="", max_length=25),
        ),
        migrations.AddField(
            model_name="bill",
            name="latest_action_description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="bill",
            name="latest_passage_date",
            field=models.CharField(default="", max_length=25),
        ),
    ]
