# Generated by Django 3.0.5 on 2020-08-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("data", "0014_remove_person_current_role_division_id")]

    operations = [
        migrations.RemoveField(model_name="eventlocation", name="coordinates")
    ]
