# Generated by Django 3.0.5 on 2020-09-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0027_auto_20200923_1329"),
    ]

    operations = [
        migrations.AddField(
            model_name="voteevent",
            name="bills",
            field=models.ManyToManyField(
                related_name="multi_bill_votes", to="data.Bill"
            ),
        ),
    ]
