# Generated by Django 4.0.10 on 2025-08-25 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0045_auto_20240705_1812"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="voteevent",
            name="opencivicdata_voteevent_dedupe__75a90b_idx",
        ),
        migrations.AlterField(
            model_name="jurisdiction",
            name="latest_bill_update",
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="jurisdiction",
            name="latest_people_update",
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="personoffice",
            name="classification",
            field=models.CharField(
                choices=[
                    ("district", "District Office"),
                    ("district-mail", "District Mailing Address"),
                    ("capitol", "Capitol Office"),
                    ("capitol-mail", "Capitol Mailing Address"),
                    ("primary", "Primary Office"),
                    ("home", "Home"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="voteevent",
            index=models.Index(
                fields=["dedupe_key"], name="opencivicda_dedupe__75a90b_idx"
            ),
        ),
    ]
