# Generated by Django 3.2.8 on 2021-11-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_alter_organization_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='citations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
