# Generated by Django 3.2.14 on 2024-11-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20240705_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personoffice',
            name='classification',
            field=models.CharField(choices=[('district', 'District Office'), ('district-mail', 'District Mailing Address'), ('capitol', 'Capitol Office'), ('capitol-mail', 'Capitol Mailing Address'), ('primary', 'Primary Office'), ('home', 'Home')], max_length=20),
        ),
    ]
