# Generated by Django 3.2.14 on 2024-11-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_alter_personoffice_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='identifier',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='billaction',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='billdocument',
            name='classification',
            field=models.TextField(blank=True, choices=[('', 'Unknown'), ('fiscal-note', 'Fiscal Note'), ('committee-report', 'Committee Report'), ('summary', 'Summary'), ('digest', 'Digest'), ('veto-message', 'Veto Message'), ('analysis', 'Analysis'), ('law', 'Law')]),
        ),
        migrations.AlterField(
            model_name='billdocument',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='billidentifier',
            name='identifier',
            field=models.TextField(help_text='A unique identifier developed by an upstream or third party source.'),
        ),
        migrations.AlterField(
            model_name='billsponsorship',
            name='classification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='billversion',
            name='classification',
            field=models.TextField(blank=True, choices=[('', 'Unknown'), ('filed', 'Filed'), ('introduced', 'Introduced'), ('amendment', 'Amendment'), ('substituted', 'Substituted'), ('enrolled', 'Enrolled'), ('became-law', 'Became Law')]),
        ),
        migrations.AlterField(
            model_name='billversion',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='classification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='dedupe_key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='upstream_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventagendamedia',
            name='classification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventagendamedia',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='classification',
            field=models.TextField(blank=True, choices=[('agenda', 'Agenda'), ('minutes', 'Minutes'), ('transcript', 'Transcript'), ('testimony', 'Testimony')]),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='classification',
            field=models.TextField(blank=True, choices=[('audio recording', 'Audio Recording'), ('video recording', 'Video Recording')]),
        ),
        migrations.AlterField(
            model_name='eventmedia',
            name='note',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='membership',
            name='person_name',
            field=models.TextField(blank=True, default='', help_text='The name of the Person that is a member of the Organization.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.TextField(blank=True, help_text='The role that the member fulfills in the Organization.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='classification',
            field=models.TextField(blank=True, choices=[('legislature', 'Legislature'), ('executive', 'Executive'), ('upper', 'Upper Chamber'), ('lower', 'Lower Chamber'), ('party', 'Party'), ('committee', 'Committee'), ('government', 'Government')], help_text='The type of Organization being defined.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(help_text='The name of the Organization.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.TextField(blank=True, default='', help_text='The official email address of the Person.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.TextField(blank=True, help_text="A Person's family name."),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.TextField(blank=True, help_text="A Person's gender"),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.TextField(blank=True, help_text="A Person's given name."),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.TextField(db_index=True, help_text="A Person's preferred full name."),
        ),
        migrations.AlterField(
            model_name='person',
            name='primary_party',
            field=models.TextField(default='', help_text='Primary party an individual is associated with.'),
        ),
        migrations.AlterField(
            model_name='personname',
            name='name',
            field=models.TextField(db_index=True, help_text='An alternative name.'),
        ),
        migrations.AlterField(
            model_name='personname',
            name='note',
            field=models.TextField(blank=True, help_text='A short, optional note about alternative name.'),
        ),
        migrations.AlterField(
            model_name='personoffice',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personoffice',
            name='classification',
            field=models.TextField(choices=[('district', 'District Office'), ('district-mail', 'District Mailing Address'), ('capitol', 'Capitol Office'), ('capitol-mail', 'Capitol Mailing Address'), ('primary', 'Primary Office'), ('home', 'Home')]),
        ),
        migrations.AlterField(
            model_name='personoffice',
            name='fax',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personoffice',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personoffice',
            name='voice',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='personvote',
            name='option',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No'), ('absent', 'Absent'), ('abstain', 'Abstain'), ('not voting', 'Not Voting'), ('paired', 'Paired'), ('excused', 'Excused'), ('other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='personvote',
            name='voter_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.TextField(help_text='A label describing the Post.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='role',
            field=models.TextField(blank=True, help_text='The function that the holder of the post fulfills.'),
        ),
        migrations.AlterField(
            model_name='relatedbill',
            name='identifier',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relatedbill',
            name='legislative_session',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='relatedbill',
            name='relation_type',
            field=models.TextField(choices=[('companion', 'Companion'), ('prior-session', 'Prior Session'), ('replaced-by', 'Replaced By'), ('replaces', 'Replaces'), ('related', 'Related')]),
        ),
        migrations.AlterField(
            model_name='votecount',
            name='option',
            field=models.TextField(choices=[('yes', 'Yes'), ('no', 'No'), ('absent', 'Absent'), ('abstain', 'Abstain'), ('not voting', 'Not Voting'), ('paired', 'Paired'), ('excused', 'Excused'), ('other', 'Other')]),
        ),
        migrations.AlterField(
            model_name='voteevent',
            name='dedupe_key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='voteevent',
            name='identifier',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voteevent',
            name='result',
            field=models.TextField(choices=[('pass', 'Pass'), ('fail', 'Fail')]),
        ),
    ]
