# Generated by Django 3.2.8 on 2021-12-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_alter_bill_citations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='citations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
