# Generated by Django 4.0.10 on 2025-08-25 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        (
            "data",
            "0046_remove_voteevent_opencivicdata_voteevent_dedupe__75a90b_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurisdiction",
            name="latest_bill_update",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 1, 1, 0, 0, tzinfo=utc)
            ),
        ),
        migrations.AlterField(
            model_name="jurisdiction",
            name="latest_people_update",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 1, 1, 0, 0, tzinfo=utc)
            ),
        ),
    ]
