# Generated by Django 3.2.8 on 2022-01-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_alter_bill_citations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='citations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
