# Generated by Django 3.2.2 on 2022-01-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0048_alter_bill_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='importobjects',
            name='records',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
