# Generated by Django 3.2.8 on 2022-02-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_importobjects_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='classification',
            field=models.CharField(blank=True, choices=[('legislature', 'Legislature'), ('executive', 'Executive'), ('upper', 'Upper Chamber'), ('lower', 'Lower Chamber'), ('party', 'Party'), ('committee', 'Committee'), ('government', 'Government'), ('subcommittee', 'Subcommittee'), ('judicial', 'Judicial')], help_text='The type of Organization being defined.', max_length=100),
        ),
    ]
