name: Build and push Docker images
on:
  push:
    branches:
      - main
    tags:
      - '*'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: "openstates/core:latest,openstates/core:${{ github.sha }}"
          push: true
  publish-plural:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: civic-eagle-enview-prod
          credentials_json: "${{ secrets.PLURAL_OPEN_REPO_PUSHER_KEY }}"
      - name: Setup Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
      - name: Docker Auth
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      - name: Build and Push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: "us-central1-docker.pkg.dev/civic-eagle-enview-prod/open-containers/core:latest,us-central1-docker.pkg.dev/civic-eagle-enview-prod/open-containers/core:${{ github.sha }}"
          push: true
